run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - misspell
    - gofmt
    - unparam
    - bodyclose
    - noctx

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam

issues:
  exclude-dirs:
    - internal/admin/dist
  max-issues-per-linter: 50
  max-same-issues: 3

